name: CI-CD

on: 
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        working-directory: portfolio
        run: yarn install --frozen-lockfile

      - name: Formatting, linting & Testing
        working-directory: portfolio
        run: |
          yarn run lint
  